id: PF2922F4F
initial_creation_type: ocr
source_metadata:
  volumes:
    96ad29369020409db0601d3cc217ca61:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: བདེན་པ་གཉིས་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1557
      volume_number: 62
